apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opa-tls
spec:
  secretName: opa-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - opa.autodotes.com
