apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opa-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: opa-config
    template:
      engineVersion: v2
      data:
        config.yaml: |
          services:
            github-pages:
              url: https://zjleblanc.github.io/autodotes-policy

          bundles:
            autodotes_policy:
              service: github-pages
              resource: bundles/autodotes_policy.bundle.tar.gz
              polling:
                min_delay_seconds: 30
                max_delay_seconds: 60

          keys:
            aap:
              key: |
                {{- .public_key | indent 16 }}
              algorithm: RS256
  data:
    - secretKey: public_key
      remoteRef:
        key: gitops/opa/jwt-sign
        property: public_key
